spring:
  profiles:
    active: test
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/proud-cat-order?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234!
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
